//------------------------------------------------------------------------------
// <auto-generated />
//------------------------------------------------------------------------------

namespace OnlineExaminationSystem
{
    public partial class AddStudent
    {
        protected global::System.Web.UI.WebControls.Label lblMsg;
        protected global::System.Web.UI.WebControls.TextBox txtName;
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        protected global::System.Web.UI.WebControls.TextBox txtRoll;
        protected global::System.Web.UI.WebControls.TextBox txtMobile;
        protected global::System.Web.UI.WebControls.TextBox txtCourse;
        protected global::System.Web.UI.WebControls.TextBox txtDept;
        protected global::System.Web.UI.WebControls.Button btnAdd;
    }
}
