//------------------------------------------------------------------------------
// <auto-generated />
//------------------------------------------------------------------------------

namespace OnlineExaminationSystem
{
    public partial class CheckAnswers
    {
        protected global::System.Web.UI.WebControls.Panel pnlNoSubmissions;
        protected global::System.Web.UI.WebControls.Label lblMsg;
        protected global::System.Web.UI.WebControls.Repeater rptSubmissions;
    }
}
