//------------------------------------------------------------------------------
// <auto-generated />
//------------------------------------------------------------------------------

namespace OnlineExaminationSystem
{
    public partial class LeaderboardPage
    {
        protected global::System.Web.UI.WebControls.DropDownList ddlSubject;
        protected global::System.Web.UI.WebControls.DropDownList ddlDept;
        protected global::System.Web.UI.WebControls.Panel pnlTop3;
        protected global::System.Web.UI.WebControls.Repeater rptTop3;
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
        protected global::System.Web.UI.WebControls.Repeater rptAll;
    }
}
