//------------------------------------------------------------------------------
// <auto-generated />
//------------------------------------------------------------------------------

namespace OnlineExaminationSystem
{
    public partial class NotificationsPage
    {
        protected global::System.Web.UI.ScriptManager ScriptManager1;
        protected global::System.Web.UI.WebControls.Button btnMarkAll;
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
        protected global::System.Web.UI.WebControls.Repeater rptNotifs;
    }
}
