//------------------------------------------------------------------------------
// <auto-generated />
//------------------------------------------------------------------------------

namespace OnlineExaminationSystem
{
    public partial class RecheckRequestsPage
    {
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
        protected global::System.Web.UI.WebControls.Label lblMsg;
        protected global::System.Web.UI.WebControls.Repeater rptRequests;
    }
}
