//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExaminationSystem
{
    public partial class SetFacultyPassword
    {
        protected global::System.Web.UI.WebControls.TextBox txtLoginEmail;
        protected global::System.Web.UI.WebControls.TextBox txtPassword;
        protected global::System.Web.UI.WebControls.TextBox txtConfirmPassword;
        protected global::System.Web.UI.WebControls.HiddenField hfToken;
        protected global::System.Web.UI.WebControls.Button btnSetPassword;
        protected global::System.Web.UI.WebControls.Label lblMsg;
    }
}