//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExaminationSystem
{
    public partial class SetStudentPassword
    {
        protected global::System.Web.UI.WebControls.TextBox txtLoginEmail;
        protected global::System.Web.UI.WebControls.TextBox txtPassword;
        protected global::System.Web.UI.WebControls.TextBox txtConfirmPassword;
        protected global::System.Web.UI.WebControls.HiddenField hfToken;
        protected global::System.Web.UI.WebControls.Button btnSetPassword;
        protected global::System.Web.UI.WebControls.Label lblMsg;
    }
}
