//------------------------------------------------------------------------------
// <auto-generated />
//------------------------------------------------------------------------------

namespace OnlineExaminationSystem
{
    public partial class StartExam
    {
        protected global::System.Web.UI.ScriptManager ScriptManager1;
        protected global::System.Web.UI.WebControls.Literal litExamTitle;
        protected global::System.Web.UI.WebControls.Literal litSubject;
        protected global::System.Web.UI.WebControls.Literal litMarks;
        protected global::System.Web.UI.WebControls.Button btnSubmitExam;
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
        protected global::System.Web.UI.WebControls.Panel pnlExam;
        protected global::System.Web.UI.WebControls.HiddenField hfViolations;
        protected global::System.Web.UI.WebControls.Repeater rptQuestions;
    }
}
