//------------------------------------------------------------------------------
// <auto-generated />
//------------------------------------------------------------------------------

namespace OnlineExaminationSystem
{
    public partial class StudentDashboard
    {
        protected global::System.Web.UI.WebControls.Literal litStudentName;
        protected global::System.Web.UI.WebControls.Label lblUpcoming;
        protected global::System.Web.UI.WebControls.Label lblCompleted;
        protected global::System.Web.UI.WebControls.Label lblAvgScore;
        protected global::System.Web.UI.WebControls.Label lblNotifications;
        protected global::System.Web.UI.WebControls.Panel pnlNoExams;
        protected global::System.Web.UI.WebControls.Repeater rptExams;
        protected global::System.Web.UI.WebControls.Panel pnlNoResults;
        protected global::System.Web.UI.WebControls.Repeater rptRecent;
    }
}
