//------------------------------------------------------------------------------
// <auto-generated />
//------------------------------------------------------------------------------

namespace OnlineExaminationSystem
{
    public partial class ViewSwitcher
    {
        protected global::System.Web.UI.WebControls.HyperLink hlSwitcher;
    }
}
