//------------------------------------------------------------------------------
// <auto-generated />
//------------------------------------------------------------------------------

namespace OnlineExaminationSystem
{
    public partial class ViewExam
    {
        protected global::System.Web.UI.WebControls.Label lblNotFound;
        protected global::System.Web.UI.WebControls.Literal litExamId;
        protected global::System.Web.UI.WebControls.Literal litTitle;
        protected global::System.Web.UI.WebControls.Literal litSubject;
        protected global::System.Web.UI.WebControls.Literal litSet;
        protected global::System.Web.UI.WebControls.Literal litDuration;
        protected global::System.Web.UI.WebControls.Literal litMarks;
        protected global::System.Web.UI.WebControls.Literal litStatus;
        protected global::System.Web.UI.WebControls.Literal litCreator;
        protected global::System.Web.UI.WebControls.Literal litCreated;
        protected global::System.Web.UI.WebControls.Literal litCount;
    }
}
