//------------------------------------------------------------------------------
// <auto-generated />
//------------------------------------------------------------------------------

namespace OnlineExaminationSystem
{
    public partial class ViewStudent
    {
        protected global::System.Web.UI.WebControls.Label lblNotFound;
        protected global::System.Web.UI.WebControls.Literal litId;
        protected global::System.Web.UI.WebControls.Literal litName;
        protected global::System.Web.UI.WebControls.Literal litEmail;
        protected global::System.Web.UI.WebControls.Literal litRoll;
        protected global::System.Web.UI.WebControls.Literal litCourse;
        protected global::System.Web.UI.WebControls.Literal litDept;
        protected global::System.Web.UI.WebControls.Literal litMobile;
    }
}
