//------------------------------------------------------------------------------
// <auto-generated />
//------------------------------------------------------------------------------

namespace OnlineExaminationSystem
{
    public partial class ViewFaculty
    {
        protected global::System.Web.UI.WebControls.Label lblNotFound;
        protected global::System.Web.UI.WebControls.Literal litId;
        protected global::System.Web.UI.WebControls.Literal litName;
        protected global::System.Web.UI.WebControls.Literal litLoginEmail;
        protected global::System.Web.UI.WebControls.Literal litEmail;
        protected global::System.Web.UI.WebControls.Literal litDept;
        protected global::System.Web.UI.WebControls.Literal litMobile;
        protected global::System.Web.UI.WebControls.Literal litCourse;
    }
}
