//------------------------------------------------------------------------------
// <auto-generated />
//------------------------------------------------------------------------------

namespace OnlineExaminationSystem
{
    public partial class ViewQuestion
    {
        protected global::System.Web.UI.WebControls.Label lblNotFound;
        protected global::System.Web.UI.WebControls.Literal litId;
        protected global::System.Web.UI.WebControls.Literal litType;
        protected global::System.Web.UI.WebControls.Literal litExam;
        protected global::System.Web.UI.WebControls.Literal litSubject;
        protected global::System.Web.UI.WebControls.Literal litText;
        protected global::System.Web.UI.WebControls.Literal litA;
        protected global::System.Web.UI.WebControls.Literal litB;
        protected global::System.Web.UI.WebControls.Literal litC;
        protected global::System.Web.UI.WebControls.Literal litD;
        protected global::System.Web.UI.WebControls.Literal litCorrect;
        protected global::System.Web.UI.WebControls.Literal litMarks;
    }
}
