//------------------------------------------------------------------------------
// <auto-generated />
//------------------------------------------------------------------------------

namespace OnlineExaminationSystem.Student
{
    public partial class FacultyList
    {
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
        protected global::System.Web.UI.WebControls.GridView gvFaculty;
        protected global::System.Web.UI.WebControls.Label lblMsg;
    }
}
